version: '3.9'

services:
  postgresdb:
    image: postgres:16.8
    ports:
      - $LOCAL_DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$DB_USER", "-d", "$DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    ports:
      - "6379"
    restart: unless-stopped
  backend:
    depends_on:
      postgresdb:
        condition: service_healthy
    image: ghcr.io/bluewave-labs/verifywise-backend:latest
    pull_policy: always
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    environment:
      - PORT=$BACKEND_PORT
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_PORT=$DB_PORT
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - MOCK_DATA_ON=$MOCK_DATA_ON
      - JWT_SECRET=$JWT_SECRET
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - FAIRNESS_AND_BIAS_URL=http://bias_and_fairness_backend:8000
  frontend:
    depends_on:
      - backend
    image: ghcr.io/bluewave-labs/verifywise-frontend:latest
    pull_policy: always
  bias_and_fairness_backend:
    depends_on:
      - backend
      - redis
    image: ghcr.io/bluewave-labs/verifywise-bias-and-fairness-backend:latest
    # pull_policy: always
    ports:
      - "8000"
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_PORT=$DB_PORT
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - BACKEND_URL=http://backend:$BACKEND_PORT
      - REDIS_URL=redis://redis:6379/0

volumes:
  db:
